# render.yaml
services:
  - type: web
    name: chat-app-backend
    env: node
    plan: free # 或 free, standard, etc.
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "3000" # Render 会自动设置PORT环境变量，但明确指定也无妨